keycloak:
  server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

---
spring.config.activate.on-profile: local

keycloak:
  server-url: http://localhost:18080
  realm: client-user
  client-id: townhall
  client-secret: TqY0UUnmtV71Q4fIgLO8wwMg4IBUPJbs

---
spring.config.activate.on-profile: dev
