version: '3.7'

services:
  keycloak_postgres:
    image: postgres:15.8
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    networks:
      - keycloak_network
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: '1.0'
  #          memory: 1G

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak_network
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1G

volumes:
  keycloak_postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
