### 1. user login
POST {{keycloak.base_url}}/realms/client-user/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = test1@example.com &
password = password &
grant_type = password &
client_id = {{gateway-service.client_id}} &
client_secret = {{gateway-service.client_secret}}

### 2. change password
PUT {{base_url}}/api/v1/client-user/users/password
Content-Type: application/json

{
  "email": "test1@example.com",
  "newPassword": "password2"
}

### 3. user login with new password
POST {{keycloak.base_url}}/realms/client-user/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = test1@example.com &
password = password2 &
grant_type = password &
client_id = {{gateway-service.client_id}} &
client_secret = {{gateway-service.client_secret}}
